import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import Header from '../components/header'
import Calculate from '../components/calculate'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [firstValue, setFirstValue] = useState<number>(0)
  const [partialValue, setPartialValue] = useState<number>(0)
  const [result, setResult] = useState<number>(0)
  const percentageValue: number = 100

  const calculateRuleOfThree = (): void => {
    if (partialValue && firstValue) {
      setResult((percentageValue * partialValue) / firstValue)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>rule-of-three.js</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Header />
        <Calculate
          firstValue={firstValue}
          setFirstValue={setFirstValue}
          partialValue={partialValue}
          setPartialValue={setPartialValue}
          result={result}
          calculateRuleOfThree={calculateRuleOfThree}
        />
      </main>

      <footer className={styles.footer}>
        created with 💜 by{' '}
        <a href='https://yuribrunetto.com.br'>yuri brunetto</a>
      </footer>
    </div>
  )
}

export default Home
